// //Manejador del evento: uncaughtException
// process.on('uncaughtException', function(err){

// 	console.log("PROGRAMA ABORTADO: ERROR \n -> " + err);
// })

// console.log("Este mensaje saldr치 por consola");

// funcionIndefinida(); //Funcion indefinida -> Error

// console.log("Este mensaje NO saldr치 por consola");

//Usar try - catch

console.log("Este mensaje saldr치 por consola");
try{
	//throw("MI EXCEPTION");
	//funcionIndefinida();
	throw new Error("my error");
}catch(err){
	console.log("ERROR CAPTURADO: ERROR \n -> " + err);
}finally{
	console.log("Hola finally");
}

console.log("Este mensaje SI saldr치 por consola");